import 'package:flutter/material.dart';
import 'package:restaurant_app/helper/asset_helper.dart';

class Product {
  Product({
    required this.uri,
    required this.price,
    required this.star,
    required this.name,
    required this.shortDesc,
    required this.numberOfRate,
    this.ingredients,
  });

  UniqueKey? id = UniqueKey();
  String uri;
  double price;
  double star;
  String name;
  String shortDesc;
  String numberOfRate;
  List<String>? ingredients;

  static List<Product> productList = [
    Product(
        uri: AssetHelper.imageSalmonSalad,
        price: 100000,
        star: 4.5,
        name: 'Salmon Salad',
        shortDesc: 'Baked salmon fish',
        numberOfRate: "25+",
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.5,
        name: 'Salmon Pizza',
        shortDesc: 'Baked salmon Pizza',
        numberOfRate: "25+",
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonSalad,
        price: 100000,
        star: 4.5,
        name: 'Salmon Salad',
        shortDesc: 'Baked salmon fish',
        numberOfRate: "25+",
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.5,
        name: 'Salmon Pizza',
        shortDesc: 'Baked salmon Pizza',
        numberOfRate: "25+",
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
  ];
  static List<Product> mealList = [
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.2,
        name: 'Beef Steak',
        shortDesc: 'Grilled beef steak',
        numberOfRate: '15+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.0,
        name: 'Chicken Wings',
        shortDesc: 'Spicy chicken wings',
        numberOfRate: '20+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.7,
        name: 'Pork Ribs',
        shortDesc: 'Slow-cooked pork ribs',
        numberOfRate: '10+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.4,
        name: 'Lamb Chops',
        shortDesc: 'Grilled lamb chops',
        numberOfRate: '12+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.6,
        name: 'BBQ Pulled Pork',
        shortDesc: 'Slow-cooked pulled pork with BBQ sauce',
        numberOfRate: '18+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.3,
        name: 'Turkey Sandwich',
        shortDesc: 'Roast turkey sandwich with fresh veggies',
        numberOfRate: '8+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.5,
        name: 'Bacon-Wrapped Shrimp',
        shortDesc: 'Shrimp wrapped in crispy bacon',
        numberOfRate: '14+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.1,
        name: 'Steak Fajitas',
        shortDesc: 'Sizzling steak fajitas with peppers and onions',
        numberOfRate: '16+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.4,
        name: 'Honey Glazed Ham',
        shortDesc: 'Baked honey glazed ham',
        numberOfRate: '22+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.3,
        name: 'Grilled Sausages',
        shortDesc: 'Assorted grilled sausages',
        numberOfRate: '13+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
  ];
  static List<Product> fishList = [
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.3,
        name: 'Grilled Salmon',
        shortDesc: 'Grilled salmon fillet with herbs',
        numberOfRate: '15+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.2,
        name: 'Tuna Sashimi',
        shortDesc: 'Fresh tuna sashimi slices',
        numberOfRate: '20+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.5,
        name: 'Crispy Cod',
        shortDesc: 'Crispy battered cod fish',
        numberOfRate: '12+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.6,
        name: 'Grilled Halibut',
        shortDesc: 'Grilled halibut steak with lemon butter',
        numberOfRate: '18+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.4,
        name: 'Miso-glazed Sea Bass',
        shortDesc: 'Miso-glazed sea bass fillet',
        numberOfRate: '16+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.1,
        name: 'Salmon Poke Bowl',
        shortDesc: 'Salmon poke bowl with rice and veggies',
        numberOfRate: '14+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.7,
        name: 'Lemon Butter Shrimp',
        shortDesc: 'Shrimp sautéed in lemon butter sauce',
        numberOfRate: '22+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.0,
        name: 'Baked Trout',
        shortDesc: 'Baked trout with herbs and garlic',
        numberOfRate: '10+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.2,
        name: 'Cajun Catfish',
        shortDesc: 'Cajun-spiced grilled catfish fillet',
        numberOfRate: '13+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.3,
        name: 'Teriyaki Salmon',
        shortDesc: 'Teriyaki-glazed salmon fillet',
        numberOfRate: '17+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
  ];
  static List<Product> dessertList = [
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.7,
        name: 'Chocolate Cupcake',
        shortDesc: 'Delicious chocolate cupcake with frosting',
        numberOfRate: '25+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.4,
        name: 'Strawberry Cheesecake',
        shortDesc: 'Creamy strawberry cheesecake with graham cracker crust',
        numberOfRate: '30+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.5,
        name: 'Fudgy Brownie',
        shortDesc: 'Rich and fudgy chocolate brownie',
        numberOfRate: '20+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.8,
        name: 'Classic Tiramisu',
        shortDesc: 'Traditional Italian tiramisu dessert',
        numberOfRate: '35+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.3,
        name: 'Ice Cream Sundae',
        shortDesc: 'Vanilla ice cream with toppings and whipped cream',
        numberOfRate: '22+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.9,
        name: 'Chocolate Fondue',
        shortDesc: 'Melting chocolate fondue with fruits and marshmallows',
        numberOfRate: '40+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.6,
        name: 'Homemade Apple Pie',
        shortDesc: 'Warm homemade apple pie with cinnamon',
        numberOfRate: '28+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.4,
        name: 'Fruit Tart',
        shortDesc: 'Colorful fruit tart with pastry cream',
        numberOfRate: '24+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.5,
        name: 'Vanilla Panna Cotta',
        shortDesc: 'Smooth vanilla panna cotta with raspberry sauce',
        numberOfRate: '27+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
    Product(
        uri: AssetHelper.imageSalmonPizza,
        price: 100000,
        star: 4.7,
        name: 'Crème Brûlée',
        shortDesc: 'Creamy custard dessert with caramelized sugar topping',
        numberOfRate: '32+',
        ingredients: [
          "1 pound lean ground beef",
          "1 medium onion, chopped",
          "1 teaspoon chili powder",
          "½ teaspoon salt",
          "½ teaspoon garlic powder",
          "1 (8-ounce) can tomato sauce",
          "12 taco shells",
          "6 ounces (1½ cups) shredded American or cheddar cheese",
          "2 cups shredded lettuce",
          "2 tomatoes, chopped",
          "¾ cup salsa",
          "¾ cup sour cream, if desired",
        ]),
  ];
  static List<Product> allProduct = productList + mealList + fishList;
}
