/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 /Users/selinanguyen/Documents/Web/JS/Test_Leadcode/my-app/public/scene.gltf 
Author: Fred Drabble (https://sketchfab.com/FredDrabble)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basic-table-free-download-b749f7b039e34a7f94ed3ac2caa1cfb4
Title: basic table - free download
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Items/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[88.394, 39.562, 48.647]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.077, 0.99, 0.59]}>
        <mesh geometry={nodes['Box016_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.005, 0.003, 24.408]} />
      </group>
      <group position={[132.662, 39.562, -4.732]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.077, 0.99, 0.59]}>
        <mesh geometry={nodes['Box024_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.005, 0.003, 24.408]} />
      </group>
      <group position={[38.238, 39.562, -4.804]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.077, 0.99, 0.59]}>
        <mesh geometry={nodes['Box008_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.005, 0.003, 24.408]} />
      </group>
      <group position={[88.466, 39.562, -44.945]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.077, 0.99, 0.59]}>
        <mesh geometry={nodes['Box032_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.005, 0.003, 24.408]} />
      </group>
      <mesh geometry={nodes['Cylinder001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[85.863, 52.763, 2.071]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Cylinder002_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[86.138, 62.227, 2.184]} rotation={[-Math.PI / 2, 0, 0]} scale={1.164} />
      <mesh geometry={nodes['Plane001_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[87.445, 1.304, -1.68]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.629, 0.444, 1]} />
      <mesh geometry={nodes['Box010_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[88.492, 28.834, 52.067]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.902, 0.78, 0.441]} />
      <mesh geometry={nodes['Box011_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[101.576, 1.549, 66.739]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box012_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[88.492, 44.734, 67.37]} rotation={[-1.409, 0, Math.PI / 2]} scale={[0.067, 0.78, 0.682]} />
      <mesh geometry={nodes['Box013_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[75.5, 1.549, 66.739]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box014_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[88.492, 62.248, 69.322]} rotation={[-1.374, 0, Math.PI / 2]} scale={[0.067, 0.78, 1.646]} />
      <mesh geometry={nodes['Box015_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[100.997, 1.561, 38.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box017_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[75.528, 1.561, 38.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box018_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[136.082, 28.834, -4.83]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.902, 0.78, 0.441]} />
      <mesh geometry={nodes['Box019_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[150.754, 1.549, -17.914]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box020_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[151.385, 44.734, -4.83]} rotation={[-Math.PI / 2, 0.161, -Math.PI]} scale={[0.067, 0.78, 0.682]} />
      <mesh geometry={nodes['Box021_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[150.754, 1.549, 8.162]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box022_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[153.337, 62.248, -4.83]} rotation={[-Math.PI / 2, 0.197, -Math.PI]} scale={[0.067, 0.78, 1.646]} />
      <mesh geometry={nodes['Box023_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[122.697, 1.561, -17.335]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box025_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[122.697, 1.561, 8.134]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box002_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[20.146, 1.549, 8.379]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box003_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[19.515, 44.734, -4.705]} rotation={[-Math.PI / 2, -0.161, 0]} scale={[0.067, 0.78, 0.682]} />
      <mesh geometry={nodes['Box005_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[17.563, 62.248, -4.705]} rotation={[-Math.PI / 2, -0.197, 0]} scale={[0.067, 0.78, 1.646]} />
      <mesh geometry={nodes['Box004_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[20.146, 1.549, -17.697]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box009_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[48.203, 1.561, -17.669]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[34.818, 28.834, -4.705]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.902, 0.78, 0.441]} />
      <mesh geometry={nodes['Box006_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[48.203, 1.561, 7.799]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box026_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[88.368, 28.834, -48.365]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.902, 0.78, 0.441]} />
      <mesh geometry={nodes['Box027_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[75.283, 1.549, -63.037]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box028_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[88.368, 44.734, -63.668]} rotation={[-1.732, 0, -Math.PI / 2]} scale={[0.067, 0.78, 0.682]} />
      <mesh geometry={nodes['Box029_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[101.359, 1.549, -63.037]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.13, 0.084, 13.479]} />
      <mesh geometry={nodes['Box030_07_-_Default_0'].geometry} material={materials['07_-_Default']} position={[88.368, 62.248, -65.62]} rotation={[-1.768, 0, -Math.PI / 2]} scale={[0.067, 0.78, 1.646]} />
      <mesh geometry={nodes['Box031_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[75.863, 1.561, -34.98]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.131, 0.077, 5.088]} />
      <mesh geometry={nodes['Box033_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[101.331, 1.561, -34.98]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.131, 0.077, 5.088]} />
    </group>
  )
}

useGLTF.preload('/Items/scene.gltf')
